### ISSUE TITLE
Compatibility with Python 3.10

### ISSUE THREAD

**Issue by amotl** [justengel/dataclass_property#3]
Dear Justin,

thanks a stack for conceiving this sweet package.

We just wanted to report to you, that, while working on https://github.com/panodata/grafanimate/pull/13, we found that when the library is used on Python 3.10, it croaks like [1], while it works on all of Python {3.7, 3.8, 3.9}.

With kind regards,
Andreas.

[1] https://github.com/panodata/grafanimate/runs/4270217110

---

```python
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_model.py _____________________
tests/test_model.py:8: in <module>
    from grafanimate.model import AnimationSequence, SequencingMode
grafanimate/model.py:35: in <module>
    class AnimationSequence:
.venv/lib/python3.10/site-packages/dataclass_property/internals.py:124: in dataclass
    return wrap(cls)
.venv/lib/python3.10/site-packages/dataclass_property/internals.py:116: in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
.venv/lib/python3.10/site-packages/dataclass_property/internals.py:346: in _process_class
    _init_fn(flds,
E   TypeError: _init_fn() missing 2 required positional arguments: 'self_name' and 'globals'
=========================== short test summary info ============================
ERROR tests/test_model.py - TypeError: _init_fn() missing 2 required position...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.24s ===============================
```

**Comment by justengel** [comment]
Thanks for notifying me of this issue. This should be fixed in version 1.3.0+
